export { merge } from 'webpack-merge';
export { default as dotenv } from 'dotenv';
export { default as HtmlWebpackPlugin } from 'html-webpack-plugin';
export { default as MiniCssExtractPlugin } from 'mini-css-extract-plugin';
export { default as CopyPlugin } from 'copy-webpack-plugin';
export { default as AssetsPlugin } from 'assets-webpack-plugin';
export { default as ESLintPlugin } from 'eslint-webpack-plugin';
export { default as resolvePlugin } from 'resolve';
export { default as ForkTsCheckerWebpackPlugin } from 'fork-ts-checker-webpack-plugin';
export { default as getCSSModuleLocalIdent } from 'react-dev-utils/getCSSModuleLocalIdent';
